### ISSUE TITLE
pybtex deprecation warning

### ISSUE THREAD

**Issue by kakila** [VorpalBlade/pelican-cite#19]
When using the plugin I get
`Person.get_part(abbr=True) is deprecated since 0.19: use pybtex.textutils.abbreviate()`

I tried using the suggested function in pelican-cite/author_year.py but then I get the error

`CRITICAL: TypeError: expected string or bytes-like object`

Anyways, for entries for this type

```
@misc{Octave,
author = {{Octave community}},
keywords = {Octave,Software},
title = {{GNU Octave 4.2.0}},
url = {www.gnu.org/software/octave/},
year = {2017},
note = {Last accessed Sept. 23, 2017},
}
```

I am getting the name rendered without the space, e.g. "Octavecommunity"

**Comment by VorpalBlade** [comment]
Which version of pelican-cite are you using and how did you install it? This should have been fixed quite some time ago.

EDIT: That is, the first issue of the deprecation warning should be fixed. I don't know about the second issue. I will have to check on that later during the coming week, as I'm very busy until Tuesday.

**Comment by kakila** [comment]
I am using the version that is in the pelican-plugins repositories. That's commit 07c61b42697a1234ca39d6f19c2e6488453383c7

**Comment by VorpalBlade** [comment]
Yes, that is old and outdated. I will figure out how to get them to update the submodule reference to a more recent version (as this was most recently done by the previous maintainer of this plugin, not by me), though again, it will take a couple of days before I have time.

If you need the fix urgently I suggest manually updating the submodule for pelican-cite, though since it is a sub-module this will likely require some basic knowledge of branches in git as sub-module checkouts by default are not attached to a branch. So something like (in the pelican-cite directory) `git checkout master && git pull` will likely be required.

**Comment by kakila** [comment]
Oh, do not worry, I can clone your repo directly.
